### ISSUE TITLE
Verge improvements

### ISSUE THREAD

**Issue by AndyGura** [marcos2250/tnfs-1995#1]
First of all, thank you for this great project, really looking forward to see it finished. Potentially it can give a huge boost to at least two projects: [OpenNFS](https://github.com/OpenNFS/OpenNFS) and mine [TNFS web](https://tnfsw.guraklgames.com/)

I investigate TRI format at the moment, and at least one newly found field can be used for your project: https://github.com/AndyGura/nfs-resources-converter/blob/main/resources/README.md#roadsplinepoint please check field `verge_slide`, which is not in use yet in your code. And can I somehow reach out to you? I can help with parsers for files, and maybe you can help me build your project for webassembly and use in my NFS web project?

Thanks

**Comment by marcos2250** [comment]
Hi Andy, sorry for the late answer. I am so glad that you liked my project.
Yes, I also really enjoyed your work, your parser was very useful for understanding PBS and TRI data, and your Web TNFS is absolutely jaw-dropping!
you found that I wasn't using all the track data available from TRI file, so now I fixed by adding verge_slide which is exactly a enum of the shoulder section friction type (asphalt, gravel, etc).
I'm also looking at unk0 (seems to be more of some kind of sound flag for fence type) and item_mode (still searching for its usage in PSX and PC executables).
Looking forward to collaborate, might rewrite parts from the old style C code to your framework with updated floating point maths.
thanks for the heads up!

**Comment by AndyGura** [comment]
Sounds good! item_mode is used as a modifier of mesh when building track 3d model, for some sound effects during gameplay. I did not find cases where it affects physics, but who knows. I'll appreciate if you let me know about your new findings about any fields, which are not documented in my parser. Thanks!
